"""empty message

Revision ID: 992c3f95a0bd
Revises: 7141f9911b21
Create Date: 2021-08-20 10:57:48.690620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992c3f95a0bd'
down_revision = '7141f9911b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
